version: '3.8'

services:
  app:
    build: .
    container_name: lumu_app
    command: flask run --host=0.0.0.0 --port=8043 
    environment:
      - FLASK_ENV=development

    volumes:
      - .:/usr/src/app # this volume if for debug the app in real time
    ports:
      - "8043:8043"
    env_file:
      - ./.env