version: '3.8'

services:
  app:
    build: .
    container_name: lumu_app
    volumes:
      - .:/app # this volume if for debug the app in real time
    ports:
      - "8043:8043"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: lumu_db
    volumes:
      - ./data:/root/db
    command: "tail -f /dev/null"
